### ISSUE TITLE
Malicious code included in v1.0.3

### ISSUE THREAD

**Issue by lenon** [cryptice/Passgen#2]
A new release was published on RubyGems with malicious code in it. Looks like a backdoor:

https://rubygems.org/gems/passgen/versions/1.0.3

<img width="1030" alt="Screen Shot 2019-06-26 at 09 47 17" src="https://user-images.githubusercontent.com/64386/60183180-29c77100-97fc-11e9-8b38-da98cca46f89.png">

This repo is not updated since 2010, so I found it weird that a new release was published without any commits here. I downloaded the gem and found this code injected in `lib/passgen/probabilities.rb`.

**Comment by fiedl** [comment]
Thank you!

**Comment by lenon** [comment]
Just an update about this issue: I contacted RubyGems staff and `passgen` was removed from there.

**Comment by sg552** [comment]
@lenon  Thank you so much!!!    1.0.2 looks good. 1.0.3 is too dangerous.

**Comment by artemv** [comment]
@lenon cool stuff, thank you! Wonder how you noticed it?

**Comment by FunkyloverOne** [comment]
So it's not on RubyGems anymore, what do you guys do? Lock to specific GitHub commit? Do a fork?

**Comment by lenon** [comment]
@FunkyloverOne in my case I was able to remove it altogether. I changed the code to use `SecureRandom.alphanumeric` from Ruby.

**Comment by IotaSpencer** [comment]
I'm probably going to make a fork and push a passgen-reborn or something similar

**Comment by cryptice** [comment]
Hi, haven't been active for a while but if possible I would like to resurrect Passgen here. Is it enough to kill v1.0.3 and do a new release v1.0.4 without the malicious code?

**Comment by IotaSpencer** [comment]
well all versions have been yanked, so i'd assume so, but i don't know how the account is managed so i don't know if you can push new releases to it

**Comment by IotaSpencer** [comment]
if you're able to get back on it, i'll gladly send some commits and fixes your way

**Comment by cryptice** [comment]
I have pushed version 1.1.1 (no functional changes but I thought it would be good to bump minor to minimize confusion) to rubygems.org now. Let me know if something else needs fixing, haven't used Ruby in a couple of years so I am a bit out of touch. Also let me know if anyone wants to be included as a contributor, I'm greatful for your input and would gladly include you.

**Comment by sg552** [comment]
Please keep your email updated so that we can keep in touch for some similar cases.

**Comment by cryptice** [comment]
Will do!

**Comment by IotaSpencer** [comment]
i would appreciate being added as well

**Comment by IotaSpencer** [comment]
contributor as in? push access or name/pull request contributor

**Comment by cryptice** [comment]
As a start I can add you to "authors" in the gemspec and mention people who have commited to the repo in the README. Eventually I'd be happy to add you as maintainer on Github (as long as you promise not to include malware...) since I'm not an active Ruby developer anymore.

**Comment by IotaSpencer** [comment]
sounds good

**Comment by IotaSpencer** [comment]
Otherwise, I do promise to not include malware, backdoors, trojans, and other hijackery into `passgen`

**Comment by cryptice** [comment]
Added you to authors list in the gemspec. Let me know if you have ideas for major additions and I will make you a contributor on Github, smaller things are maybe easier via pull requests.
